"""sqlite-vec backed memory scaffold.

Phase 1: basic store/search surface. Full RAG integration is deferred.
Embeddings are generated by a pluggable callable; when none is supplied, a
deterministic hash-based fallback is used so the scaffold is usable without
extra model downloads.
"""

from __future__ import annotations

import hashlib
import json
import logging
import sqlite3
import struct
from pathlib import Path
from typing import Any, Callable, Iterable, Optional

logger = logging.getLogger(__name__)

EMBED_DIM = 384
Embedder = Callable[[str], list[float]]


def _fallback_embed(text: str, dim: int = EMBED_DIM) -> list[float]:
    """Deterministic hash-based embedding used only as a scaffold placeholder."""
    vec: list[float] = []
    i = 0
    while len(vec) < dim:
        digest = hashlib.sha256(f"{i}:{text}".encode()).digest()
        for j in range(0, len(digest), 4):
            if len(vec) >= dim:
                break
            val = struct.unpack("<I", digest[j : j + 4])[0] / 0xFFFFFFFF
            vec.append(val * 2.0 - 1.0)
        i += 1
    return vec


class Memory:
    """SQLite + sqlite-vec backed embedding store."""

    def __init__(
        self,
        db_path: str | Path = "agent_memory.db",
        embedder: Optional[Embedder] = None,
        dim: int = EMBED_DIM,
    ) -> None:
        self.db_path = str(db_path)
        self.dim = dim
        self._embedder: Embedder = embedder or (lambda t: _fallback_embed(t, dim))
        self._conn: Optional[sqlite3.Connection] = None

    def connect(self) -> sqlite3.Connection:
        if self._conn is not None:
            return self._conn
        conn = sqlite3.connect(self.db_path)
        conn.enable_load_extension(True)
        try:
            import sqlite_vec  # type: ignore

            sqlite_vec.load(conn)
        except ImportError:
            logger.warning("sqlite-vec not installed; vector search disabled")
        finally:
            conn.enable_load_extension(False)
        self._init_schema(conn)
        self._conn = conn
        return conn

    def close(self) -> None:
        if self._conn is not None:
            self._conn.close()
            self._conn = None

    def _init_schema(self, conn: sqlite3.Connection) -> None:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS memories (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                text TEXT NOT NULL,
                metadata TEXT NOT NULL DEFAULT '{}',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        try:
            conn.execute(
                f"CREATE VIRTUAL TABLE IF NOT EXISTS memory_vec USING vec0("
                f"embedding float[{self.dim}])"
            )
        except sqlite3.OperationalError as exc:
            logger.warning("Could not create vec0 table: %s", exc)
        conn.commit()

    def store_embedding(
        self, text: str, metadata: Optional[dict[str, Any]] = None
    ) -> int:
        conn = self.connect()
        embedding = self._embedder(text)
        cur = conn.execute(
            "INSERT INTO memories (text, metadata) VALUES (?, ?)",
            (text, json.dumps(metadata or {})),
        )
        rowid = cur.lastrowid
        try:
            conn.execute(
                "INSERT INTO memory_vec (rowid, embedding) VALUES (?, ?)",
                (rowid, self._serialize(embedding)),
            )
        except sqlite3.OperationalError as exc:
            logger.warning("vec0 insert failed: %s", exc)
        conn.commit()
        return int(rowid)

    def search(self, query: str, top_k: int = 5) -> list[dict[str, Any]]:
        conn = self.connect()
        embedding = self._embedder(query)
        try:
            rows = conn.execute(
                """
                SELECT memories.id, memories.text, memories.metadata, distance
                FROM memory_vec
                JOIN memories ON memories.id = memory_vec.rowid
                WHERE embedding MATCH ?
                ORDER BY distance
                LIMIT ?
                """,
                (self._serialize(embedding), top_k),
            ).fetchall()
        except sqlite3.OperationalError as exc:
            logger.warning("vec0 search unavailable (%s); falling back to recency", exc)
            rows = conn.execute(
                "SELECT id, text, metadata, 0.0 FROM memories ORDER BY id DESC LIMIT ?",
                (top_k,),
            ).fetchall()
        return [
            {
                "id": r[0],
                "text": r[1],
                "metadata": json.loads(r[2] or "{}"),
                "distance": r[3],
            }
            for r in rows
        ]

    @staticmethod
    def _serialize(vec: Iterable[float]) -> bytes:
        data = list(vec)
        return struct.pack(f"{len(data)}f", *data)
